### Crear usuario
POST http://localhost:3000/users/create
Content-Type: application/json

{
  "displayName": "Test User",
  "username": "test",
  "password": "123",
  "email": "test@gmail.com"
}

### 

GET http://localhost:3000/pins/6840ef8fd06433b535b986c9